services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "6000:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
     - "8000:8000"
    depends_on:
      - db
    restart: always

volumes:
  db_data:
