services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "6000:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
